site_name: Git
site_url: https://devops.basics.learn.mctantwerp.be
site_author: Sam Serrien
site_description: Basis cursus over template

repo_name: mctantwerp/learn-devops-basics
repo_url: https://github.com/mctantwerp/learn-devops-basics
edit_uri: edit/main/docs/

copyright: Karel de Grote Hogeschool<br>Multimedia & Creatieve Technologie

nav:
  - üëã Introductie: index.md
  - Git Basics:
    - git/basics/index.md
    - git/basics/repositories.md
    - git/basics/stage-commit-push.md
    - git/basics/clone-pull.md
  - Samenwerken:
    - git/collaboration/index.md
    - git/collaboration/blame.md
    - git/collaboration/merge-conflicts.md
    - git/collaboration/pull-requests.md
  - Branches:
    - git/branches/index.md
    - git/branches/workflows.md
    - git/branches/advanced.md
  - Extra Git Tools:
    - git/tools/gitignore.md
    - git/tools/stash.md
    - git/tools/tags.md
    - git/tools/rebase.md
    - git/tools/cherry-pick.md
  - ‚ùì Appendix:
    - appendix/resources.md
    - appendix/commands-cheatsheet.md

theme:
  name: material

  logo: _resources/graphics/logo_full.png
  favicon: _resources/graphics/favicon.ico

  language: nl
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.top
    - navigation.indexes
    - content.code.annotate
    - search.highlight
    - search.share
    - search.suggest
    - content.tooltips

  icon:
    repo: fontawesome/brands/github
  palette:
    primary: black
    accent: cyan

plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      repository: mctantwerp/learn-welkom
      branch: develop
      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]

extra_css:
  - _resources/styles/main.css

extra_javascript:
  - _resources/scripts/main.js

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  analytics:
    provider: google
    property: G-ZZW6S6EENR
  generator: false
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/mct.kdg/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCVcQd6yzdN9kW16sXuN_8zQ
    - icon: fontawesome/brands/github
      link: https://github.com/mctantwerp
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/school/karel-de-grote-hogeschool/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mctantwerp
    - icon: fontawesome/brands/vimeo
      link: https://vimeo.com/mctantwerp
